<a href="https://colab.research.google.com/github/eashwardarur/DA/blob/main/DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#To raed the particular file
var=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/medical_students_dataset.csv")

In [ ]:
#To check data we have several ways
var.head()
#it gives top 5 or n dataset

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No

In [ ]:
#It gives bottom 5 or n dataset
var.tail()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
199995,NaN,24.0,Male,176.503260,95.756997,B,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,99997.0,29.0,Female,163.917675,45.225194,NaN,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,99998.0,34.0,Female,NaN,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,NaN,No
199998,99999.0,30.0,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,100000.0,20.0,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,NaN,No

In [ ]:
#It gives complete information about the datasets
var.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Student ID      180000 non-null  float64
 1   Age             180000 non-null  float64
 2   Gender          180000 non-null  object
 3   Height          180000 non-null  float64
 4   Weight          180000 non-null  float64
 5   Blood Type      180000 non-null  object
 6   BMI             180000 non-null  float64
 7   Temperature     180000 non-null  float64
 8   Heart Rate      180000 non-null  float64
 9   Blood Pressure  180000 non-null  float64
 10  Cholesterol     180000 non-null  float64
 11  Diabetes        180000 non-null  object
 12  Smoking         180000 non-null  object
dtypes: float64(9), object(4)
memory usage: 19.8+ MB

In [ ]:
#It gives statisital summary about the dataset
var.describe()

,Student ID,Age,Height,Weight,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol
count,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000
mean,49974.042078,26.021561,174.947103,69.971585,23.338869,98.600948,79.503767,114.558033,184.486361
std,28879.641657,4.890528,14.447560,17.322574,7.033554,0.500530,11.540755,14.403353,37.559678
min,1.000000,18.000000,150.000041,40.000578,10.074837,96.397835,60.000000,90.000000,120.000000
25%,24971.750000,22.000000,162.476110,54.969838,17.858396,98.264750,70.000000,102.000000,152.000000
50%,49943.500000,26.000000,174.899914,69.979384,22.671401,98.599654,80.000000,115.000000,184.000000
75%,74986.000000,30.000000,187.464417,84.980097,27.997487,98.940543,90.000000,127.000000,217.000000
max,100000.000000,34.000000,199.998639,99.999907,44.355113,100.824857,99.000000,139.000000,249.000000

In [ ]:
#To get the random samples from dataset
var.sample(5)

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
151920,51921.0,22.0,Female,179.094279,NaN,AB,30.808573,98.219658,83.0,97.0,191.0,No,No
18876,18877.0,25.0,Female,176.481100,63.957329,B,20.534963,NaN,63.0,131.0,131.0,No,Yes
129373,29374.0,21.0,Male,186.209321,72.236611,B,20.833130,NaN,96.0,135.0,174.0,No,No
190970,90971.0,33.0,Female,197.013429,86.530119,B,22.293366,97.681152,63.0,107.0,191.0,No,No
131517,31518.0,33.0,Male,167.846450,71.094565,B,25.235510,99.108232,89.0,97.0,158.0,No,Yes

In [ ]:
#Some inbuit methods in pandas
#Unique method returns the unique values from the specific column
var['Heart Rate'].unique()

array([95., 93., 76., 99., 70., 66., 85., nan, 61., 60., 86., 62., 89.,
       68., 63., 78., 92., 82., 64., 81., 96., 98., 80., 77., 67., 74.,
       75., 73., 84., 65., 97., 90., 87., 88., 69., 94., 71., 79., 72.,
       91., 83.])

In [ ]:
#Value_counts gives the unique values with the no of occurances
var.value_counts('Age')

Age
28.0    10882
27.0    10755
33.0    10703
22.0    10691
25.0    10683
21.0    10677
29.0    10676
34.0    10660
24.0    10600
20.0    10566
31.0    10541
32.0    10510
26.0    10486
30.0    10439
19.0    10413
18.0    10383
23.0    10335
Name: count, dtype: int64

In [ ]:
#Sort_values method sorts the datasets on the basics of col-name
var.sort_values(by='Height',ascending=False)
#ascending=False arranges the data in decending order

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
95061,95062.0,32.0,Male,199.998639,62.329452,B,15.582575,97.837022,81.0,114.0,223.0,No,Yes
87278,87279.0,33.0,Male,199.997940,56.613007,O,14.153543,98.720398,79.0,107.0,210.0,Yes,Yes
187278,87279.0,33.0,Male,199.997940,56.613007,O,NaN,98.720398,79.0,NaN,210.0,Yes,NaN
48175,48176.0,NaN,Female,199.996965,72.792448,B,18.198664,99.150429,65.0,NaN,135.0,No,No
180796,80797.0,19.0,Female,199.996834,68.418014,B,17.105045,98.772037,67.0,130.0,171.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199958,99959.0,24.0,Male,NaN,93.905244,B,30.570157,97.921350,82.0,NaN,134.0,No,Yes
199969,99970.0,24.0,Male,NaN,43.256927,AB,12.003793,NaN,88.0,136.0,206.0,No,No
199972,99973.0,34.0,Male,NaN,80.188752,AB,21.270517,98.853214,81.0,117.0,244.0,No,No
199993,99994.0,22.0,Male,NaN,46.155224,A,NaN,98.331019,93.0,100.0,NaN,Yes,No
199997,99998.0,34.0,Female,NaN,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,NaN,No

In [ ]:
var.sort_values(by='Height',ascending=True)
#ascending=False arranges the data in ascending order

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
198250,98251.0,33.0,Male,150.000041,NaN,O,40.067844,98.468434,98.0,112.0,143.0,No,No
114789,14790.0,29.0,Female,150.000329,65.351733,NaN,29.045087,97.837193,84.0,121.0,NaN,No,No
14789,14790.0,29.0,Female,150.000329,65.351733,AB,29.045087,NaN,84.0,121.0,125.0,NaN,No
167455,67456.0,NaN,Female,150.000876,62.621752,O,27.831565,98.825301,67.0,116.0,233.0,No,No
76541,76542.0,27.0,Male,150.000996,91.408404,O,40.625418,98.523170,68.0,97.0,NaN,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199958,99959.0,24.0,Male,NaN,93.905244,B,30.570157,97.921350,82.0,NaN,134.0,No,Yes
199969,99970.0,24.0,Male,NaN,43.256927,AB,12.003793,NaN,88.0,136.0,206.0,No,No
199972,99973.0,34.0,Male,NaN,80.188752,AB,21.270517,98.853214,81.0,117.0,244.0,No,No
199993,99994.0,22.0,Male,NaN,46.155224,A,NaN,98.331019,93.0,100.0,NaN,Yes,No
199997,99998.0,34.0,Female,NaN,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,NaN,No

In [ ]:
#Attributes in pandas
#shape and columns
var.shape # returns the no of rows and columns in tuple format

(200000, 13)

In [ ]:
var.columns #Returns all the columns in the form of list

Index(['Student ID', 'Age', 'Gender', 'Height', 'Weight', 'Blood Type', 'BMI',
       'Temperature', 'Heart Rate', 'Blood Pressure', 'Cholesterol',
       'Diabetes', 'Smoking'],
      dtype='object')

In [ ]:
##Data Cleaning
#Data cleaning in pandas is the process of fixing messy, inconsistent, or incomplete datasets to prepare them for analysis. Since real-world data is rarely perfect, analysts often spend 70–80% of their time on these cleaning steps


#Inspect Datadf.info(), df.head(), df.describe()
#Null Valuesdf.isna(), df.fillna(), df.dropna()
#Duplicatesdf.duplicated(), df.drop_duplicates()
#Format Stringsdf['col'].str.lower(), .str.strip(), .str.replace()
#Column Opsdf.rename(), df.drop(), df.astype()

In [ ]:
#Data Cleaning
import pandas as pd
var=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/medical_students_dataset.csv")
var.fillna(var['Age'].mean())

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.000000,18.000000,Female,161.777924,72.354947,O,27.645835,26.021561,95.0,109.000000,203.0,No,26.021561
1,2.000000,26.021561,Male,152.069157,47.630941,B,26.021561,98.714977,93.0,104.000000,163.0,No,No
2,3.000000,32.000000,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.000000,216.0,Yes,No
3,26.021561,30.000000,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.000000,141.0,No,Yes
4,5.000000,23.000000,Female,26.021561,46.234173,O,26.021561,98.480008,95.0,26.021561,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,26.021561,24.000000,Male,176.503260,95.756997,B,30.737254,99.170685,65.0,121.000000,130.0,No,No
199996,99997.000000,29.000000,Female,163.917675,45.225194,26.021561,16.831734,97.865785,62.0,125.000000,198.0,No,Yes
199997,99998.000000,34.000000,Female,26.021561,99.648914,26.021561,33.189303,98.768210,60.0,90.000000,154.0,26.021561,No
199998,99999.000000,30.000000,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.000000,225.0,No,No
199999,100000.000000,20.000000,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.000000,132.0,26.021561,No

In [ ]:
var.drop_duplicates()

,Student ID,Age,Gender,Height,Weight,Blood Type,BMI,Temperature,Heart Rate,Blood Pressure,Cholesterol,Diabetes,Smoking
0,1.0,18.0,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,2.0,NaN,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,3.0,32.0,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,NaN,30.0,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,5.0,23.0,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,NaN,24.0,Male,176.503260,95.756997,B,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,99997.0,29.0,Female,163.917675,45.225194,NaN,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,99998.0,34.0,Female,NaN,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,NaN,No
199998,99999.0,30.0,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,100000.0,20.0,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,NaN,No

In [ ]:
#To replacve all the null values with mean
cols=var.select_dtypes(include=['int64','float64']).columns
for i in cols:
  var[i]=var[i].fillna(var[i].mean())
#only int and float have been replaced

In [ ]:
#this returns the col name and no of null values
var.isnull().sum()

Student ID            0
Age                   0
Gender            20000
Height                0
Weight                0
Blood Type        20000
BMI                   0
Temperature           0
Heart Rate            0
Blood Pressure        0
Cholesterol           0
Diabetes          20000
Smoking           20000
dtype: int64

In [ ]:
#To replacve all the null values with mean
cols1=var.select_dtypes(include=['object']).columns
for i in cols1:
  var[i]=var[i].fillna(var[i].mode())
var.isnull().sum()

Student ID            0
Age                   0
Gender            20000
Height                0
Weight                0
Blood Type        20000
BMI                   0
Temperature           0
Heart Rate            0
Blood Pressure        0
Cholesterol           0
Diabetes          20000
Smoking           19999
dtype: int64

In [1]:
import pandas as pd
var=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/medical_students_dataset.csv")

In [7]:
#Fill NaN values with the mean (or 0, or median)
var["Age"] = var["Age"].fillna(var["Age"].mean())
#converting dtype of age to int coz age cant be in float
var["Age"] = var["Age"].astype(int)
#to print and check
print(var["Age"].isnull().sum())

0

In [11]:
#Fill NaN values with the mean (or 0, or median)
var["Student ID"] = var["Student ID"].fillna(var["Student ID"].mean())
#converting dtype of student id to int coz student id cant be in float
var["Student ID"] = var["Student ID"].astype(int)#astype converts to praticular datatype which is passed in ()
#to print and check
print(var["Student ID"].isnull().sum())

0

In [14]:
#cleaning the text types
cols=var.select_dtypes(include=['string']).columns
for col in cols:
  var[col]=var[col].str.lower()
#Any irrelevant data or mixed of upper and lower cases

In [15]:
#To drop duplicates
var=var.drop_duplicates()

In [16]:
#Rename/standarlize the col names
var.columns=var.columns.str.strip()#it removes all the spaces from col-name
var.columns=var.columns.str.lower()#all the col-names shld be in the same format of col-name

In [19]:
var.describe()

,student id,age,height,weight,bmi,temperature,heart rate,blood pressure,cholesterol
count,192260.000000,192260.000000,172355.000000,172361.000000,172361.000000,172349.000000,172358.000000,172368.000000,172369.000000
mean,49982.351097,26.019963,174.958063,69.980804,23.339061,98.601112,79.509979,114.564386,184.500096
std,27350.586787,4.631977,14.451518,17.322983,7.033517,0.500243,11.542906,14.404269,37.551665
min,1.000000,18.000000,150.000041,40.000578,10.074837,96.397835,60.000000,90.000000,120.000000
25%,27831.750000,22.000000,162.480603,54.975097,17.859856,98.264992,70.000000,102.000000,152.000000
50%,49974.000000,26.000000,174.920345,69.995078,22.670728,98.599511,80.000000,115.000000,184.000000
75%,72133.250000,30.000000,187.469633,84.987676,27.992642,98.940539,90.000000,127.000000,217.000000
max,100000.000000,34.000000,199.998639,99.999907,44.355113,100.824857,99.000000,139.000000,249.000000

In [20]:
var.sample(10)

,student id,age,gender,height,weight,blood type,bmi,temperature,heart rate,blood pressure,cholesterol,diabetes,smoking
182263,82264,18,Male,151.093023,NaN,A,20.189137,97.528460,74.0,94.0,249.0,Yes,Yes
124278,24279,27,Female,181.718567,51.404364,AB,15.566873,98.859603,85.0,128.0,194.0,No,No
44786,49974,22,Male,187.376877,92.124397,O,26.238721,98.823216,95.0,126.0,234.0,No,No
56930,56931,22,Female,198.005675,52.704161,AB,13.442797,98.240610,88.0,110.0,NaN,No,No
64941,64942,26,Male,150.623713,46.898142,A,20.671355,98.873849,80.0,NaN,136.0,Yes,No
73839,73840,29,Female,199.620343,66.137815,B,16.597407,98.238668,64.0,125.0,204.0,No,No
105993,5994,31,Male,181.322410,96.378087,A,29.314017,97.282321,70.0,137.0,NaN,No,No
159731,49974,22,Male,NaN,95.377246,A,26.714267,97.631923,66.0,98.0,NaN,No,No
54518,54519,26,Male,178.776004,46.213530,A,NaN,98.296731,64.0,NaN,202.0,No,No
55318,55319,23,NaN,182.634907,43.101840,A,NaN,98.295236,94.0,116.0,140.0,No,No

In [22]:
#incorret/ alomst impossible/inconsitence value in BMI
var.loc[var['bmi']<15,"bmi"]=var["bmi"].mean()

In [23]:
var.describe()

,age,height,weight,bmi,temperature,heart rate,blood pressure,cholesterol
count,192260.000000,172355.000000,172361.000000,172361.000000,172349.000000,172358.000000,172368.000000,172369.000000
mean,26.019963,174.958063,69.980804,24.542652,98.601112,79.509979,114.564386,184.500096
std,4.631977,14.451518,17.322983,5.970834,0.500243,11.542906,14.404269,37.551665
min,18.000000,150.000041,40.000578,15.000443,96.397835,60.000000,90.000000,120.000000
25%,22.000000,162.480603,54.975097,20.161318,98.264992,70.000000,102.000000,152.000000
50%,26.000000,174.920345,69.995078,23.339061,98.599511,80.000000,115.000000,184.000000
75%,30.000000,187.469633,84.987676,27.992642,98.940539,90.000000,127.000000,217.000000
max,34.000000,199.998639,99.999907,44.355113,100.824857,99.000000,139.000000,249.000000

In [24]:
var.sample(10)

,age,gender,height,weight,blood type,bmi,temperature,heart rate,blood pressure,cholesterol,diabetes,smoking
70373,32,Female,176.536804,75.474089,AB,24.217391,NaN,66.0,95.0,147.0,NaN,No
159229,25,Male,157.962608,89.976119,AB,36.059414,98.041525,NaN,114.0,209.0,No,No
139006,27,Male,152.152200,75.703159,AB,NaN,98.449976,61.0,129.0,128.0,No,No
5433,25,Male,175.518376,51.403117,B,16.685694,NaN,67.0,124.0,160.0,No,No
22925,18,Male,180.184639,49.184488,O,15.149302,NaN,89.0,NaN,191.0,No,Yes
176599,32,Female,165.669655,48.620207,AB,17.714580,98.442476,61.0,138.0,164.0,Yes,No
129647,29,Female,166.983053,52.882947,O,18.965786,98.537445,82.0,116.0,165.0,No,NaN
59039,18,Male,167.581599,98.717411,O,35.151276,98.509569,95.0,138.0,145.0,No,No
6149,27,Female,193.385555,53.681433,O,NaN,98.637959,66.0,NaN,239.0,NaN,NaN
154977,29,NaN,169.271671,52.999380,O,18.497040,98.542325,73.0,126.0,208.0,NaN,No

In [25]:
var

,age,gender,height,weight,blood type,bmi,temperature,heart rate,blood pressure,cholesterol,diabetes,smoking
0,18,Female,161.777924,72.354947,O,27.645835,NaN,95.0,109.0,203.0,No,NaN
1,26,Male,152.069157,47.630941,B,NaN,98.714977,93.0,104.0,163.0,No,No
2,32,Female,182.537664,55.741083,A,16.729017,98.260293,76.0,130.0,216.0,Yes,No
3,30,Male,182.112867,63.332207,B,19.096042,98.839605,99.0,112.0,141.0,No,Yes
4,23,Female,NaN,46.234173,O,NaN,98.480008,95.0,NaN,231.0,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...
199995,24,Male,176.503260,95.756997,B,30.737254,99.170685,65.0,121.0,130.0,No,No
199996,29,Female,163.917675,45.225194,NaN,16.831734,97.865785,62.0,125.0,198.0,No,Yes
199997,34,Female,NaN,99.648914,NaN,33.189303,98.768210,60.0,90.0,154.0,NaN,No
199998,30,Female,156.446944,50.142824,A,20.486823,98.994212,61.0,106.0,225.0,No,No
199999,20,Female,153.927409,99.928405,O,42.175189,98.595817,95.0,133.0,132.0,NaN,No

In [ ]:
#student id has bad entries which may effect training quality and not required while training
var=var.drop('student id',axis=1)