<a href="https://colab.research.google.com/github/eashwardarur/DA/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing
ENCODING

In [10]:
#Importing the modules
import pandas as pd
#scikit-learn its an library
from sklearn.preprocessing import LabelEncoder
#LabelEncoder is class

In [11]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [12]:
df['Product'].unique()

array(['Watch', 'Mouse', 'stove', 'shoe'], dtype=object)

In [13]:
le=LabelEncoder()

In [14]:
#fit will learn the data,identify the unique vales,sort them and map them
#transform will transfrom the data
#.fit() and .transform()
#fit_transform accepts one positional argument
df['Product']=le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2