<a href="https://colab.research.google.com/github/eashwardarur/DA/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Preprocessing
ENCODING

In [1]:
#Importing the modules
import pandas as pd
#scikit-learn its an library
from sklearn.preprocessing import LabelEncoder
#LabelEncoder is class

In [10]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe']
})
df

  Product
0   Watch
1   Mouse
2   stove
3    shoe
4   stove
5   Mouse
6   Watch
7    shoe

In [11]:
df['Product'].unique()

array(['Watch', 'Mouse', 'stove', 'shoe'], dtype=object)

In [12]:
le=LabelEncoder()

In [13]:
#fit will learn the data,identify the unique vales,sort them and map them
#transform will transfrom the data
#.fit() and .transform()
#fit_transform accepts one positional argument
df['Product']=le.fit_transform(df['Product'])
df

   Product
0        1
1        0
2        3
3        2
4        3
5        0
6        1
7        2